// src/components/index/blogs.tsx
import type { IndexProps } from "@/interface";
import Title from "@/components/widgets/title";

export default function Blogs({ data }: IndexProps) {
  return (
    <div className="bg-bg flex flex-col items-center w-full min-h-full">
      <Title id="blogs">Recent Blogs</Title>
      <div className="flex flex-wrap justify-center lg:justify-start w-full gap-5 p-3 py-5">
        {
          data.map((b, i: number) => {
            return (
              <div
                className="flex flex-col w-[calc(90%-0.5rem)] lg:w-[calc(33.333%-1rem)] card p-3 aspect-video gap-3"
                key={`${i + 1}. ${b.title}`}>
                <span className="text-[1.25rem]">{b.title.substring(0, 70)} {b.title.length > 70 ? "..." : ""}</span>
                <span
                  // onClick={() => {
                  //   c.link ? window.open(c.link, "_blank") : c.url
                  // }}
                  className="text-justify select-none">
                  {b.content.substring(0, 150)} {b.content.length > 150 ? "..." : ""}
                </span>
              </div>
            )
          })
        }
        <button className="w-full p-3 silk card">See more</button>
      </div>
    </div >
  )
}

// src/routes/home/blogs.svelte
<script lang="ts">
	import Card from "@/components/card.svelte";
	import { get } from "@/lib/fetch.ts";
	import { onMount } from "svelte";

	let blogs: Record<string, any>[] = [];

	onMount(async () => {
		const data = await get("blog");
		blogs = data.data;
	});
</script>

<div
	id="blogs"
	class="flex flex-wrap p-2 pt-[25%] md:pt-[10%] w-full h-full gap-2 overflow-hidden overflow-y-auto snap-start"
>
	{#if blogs.length > 0}
		{#each blogs as blog}
			<Card
				class_="aspect-video w-full md:w-[calc(33.333%-0.5rem)] justify-between"
			>
				<span class="font-bold text-[1.25rem]">{blog.title}</span>
				<span class="italic text-[0.75rem]"
					>{blog.content.substring(0, 250)} ...</span
				>
			</Card>
		{/each}
		<Card
			class_="aspect-video w-full md:w-[calc(33.333%-0.5rem)] items-center justify-center"
		>
			<span class="font-bold text-[1.25rem]">See More</span>
			<span class="italic text-[0.75rem]">Click here to see more blogs</span>
		</Card>
	{:else}
		<span>No Blogs</span>
	{/if}
</div>
