// src/components/index/projects.tsx
import type { projectInterface, projectsInterface } from "@/interface";
import Title from "../widgets/title";
import { useEffect, useState } from "react";
import { retrieval } from "@/lib/api";
import Modal from "@/components/widgets/modal";
import { Link } from "react-router";

export default function Projects({ data }: { data: projectInterface }) {

  const [lists, setLists] = useState<projectsInterface[]>(data.projects)
  const [visible, setVisible] = useState(false)
  const [project, setProject] = useState<projectsInterface | null>(null)

  useEffect(() => {
    const withImg = lists.filter((p: Record<string, any>) => p.img);
    const shuffled = [...withImg].sort(() => 0.5 - Math.random());
    setLists(shuffled
      .slice(0, 6)
      .sort((a: Record<string, any>, b: Record<string, any>) =>
        a.name.localeCompare(b.name),
      ));
  }, [])

  return (
    <div className="bg-bg flex flex-col items-center w-full min-h-full">
      <Title id="projects">Random Projects</Title>
      <div className="flex flex-wrap justify-center w-full gap-2 p-3 py-5">
        {
          lists.length > 0 ?
            lists.map((p: projectsInterface, i: number) => {
              return (
                <div
                  onClick={() => {
                    setVisible(true)
                    setProject(p)
                  }}
                  className="relative w-[calc(90%-0.5rem)] lg:w-[calc(33.333%-0.5rem)] aspect-video group overflow-hidden"
                  key={`${i + 1}. ${p.name}`}>
                  <img
                    className="absolute object-cover inset-0 h-full w-full lg:dark:grayscale-100 group-hover:grayscale-0 transition delay-75"
                    src={p.img ?
                      retrieval("retrieve", { file: p.img ?? "" }) : ""} />
                  <span
                    onClick={() => {
                      p.link ? window.open(p.link, "_blank") : null
                    }}
                    className="absolute select-none cursor-pointer opacity-0 group-hover:opacity-100 bottom-0 p-3 z-10 w-full bg-bg/75 transition-all delay-75">
                    {p.name}
                  </span>
                </div>
              )
            }) : null
        }
        <Link to="/projects" className="text-center w-full p-3 silk card">See more</Link>
      </div>
      <Modal
        visible={visible}
        className="flex flex-col relative rounded-md w-2/3 aspect-video overflow-hidden"
        setVisible={setVisible}>

        {project ?
          <>
            {
              project.img ?
                <img
                  className="inset-0 w-full h-full object-fill"
                  src={project.img ? retrieval("/retrieve", { file: project.img }) : ""}
                  alt={project.name} />
                :
                <div className="flex items-center justify-center aspect-video w-full">
                  <p>Screenshot Soon</p>
                </div>
            }
            <div
              onClick={() => {
                project.link ? window.open(project.link, "_blank") : null
              }}
              className="flex flex-col absolute bottom-0 right-0 left-0 z-1 bg-input/50 backdrop-blur-md p-2 cursor-pointer">
              <span>{project.name}</span>
              <span>{project.description}</span>
            </div>
          </>
          : null
        }
      </Modal>
    </div >
  )
}

// src/routes/home/projects.svelte
<script lang="ts">
	import { retrieval } from "@/lib/fetch.ts";
	import Loader from "@/components/loader.svelte";
	import Card from "@/components/card.svelte";

	let {
		categories = ["all"],
		totalProjects = [],
		projects = $bindable([]),
		parseData = false,
	}: {
		categories?: string[];
		totalProjects?: Record<string, any>[];
		projects?: Record<string, any>[];
		parseData?: boolean;
	} = $props();

	let active = $state("all");

	function filter(category: string) {
		active = category.toLowerCase();
		if (active === "all") {
			const withImg = totalProjects.filter((p: Record<string, any>) => p.img);
			const shuffled = [...withImg].sort(() => 0.5 - Math.random());
			projects = shuffled
				.slice(0, 8)
				.sort((a: Record<string, any>, b: Record<string, any>) =>
					a.name.localeCompare(b.name),
				);
		} else {
			projects = totalProjects
				.filter((proj: Record<string, any>) =>
					proj.category.includes(active.toLowerCase()),
				)
				.sort((a: Record<string, any>, b: Record<string, any>) =>
					a.name.localeCompare(b.name),
				);
		}
	}

	$effect(() => {
		if (parseData && active === "all" && totalProjects.length > 0) {
			filter("all");
		}
	});
</script>

<div
	id="projects"
	class="flex flex-col p-2 pt-[25%] md:pt-[10%] h-full w-full overflow-y-auto select-none snap-start"
>
	<div
		class="flex gap-2 items-center md:justify-center py-10 md:p-3 overflow-hidden overflow-x-auto scrollbar-none"
	>
		{#each categories as category}
			<!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
			<li
				onclick={() => {
					filter(category);
				}}
				onkeydown={(e) => {
					if (e.key === "Enter" || e.key === " ") filter(category);
				}}
				class={`select-none cursor-pointer ${active === category.toLowerCase() ? "border border-black dark:border-white border-solid" : "bg-zinc-300 dark:bg-[#313131]"} px-2 rounded list-none text-[0.80em]`}
			>
				{#if category.length <= 3 && category !== "all"}
					{category.toUpperCase()}
				{:else if category === "all"}
					Randomized
				{:else}{category[0].toUpperCase()}{category.substring(1)}
				{/if}
			</li>
		{/each}
	</div>
	<div class="flex flex-wrap w-full gap-5 p-5">
		{#if projects.length > 0}
			{#each projects as project}
				<Card
					onclick={() => {
						window.open(project.link, "_blank");
					}}
					class="relative aspect-video w-full md:w-[calc(25%-1rem)] rounded overflow-hidden !p-0 group"
				>
					<img
						class="absolute w-full h-full md:grayscale group-hover:grayscale-0"
						src={retrieval("retrieve", { file: project.img ?? "" })}
						alt=""
					/>
					<span
						class="absolute z-1 bottom-0 left-0 right-0 bg-[#212121]/50 text-white p-2 md:opacity-0 dark:group-hover:opacity-100 group-hover:opacity-100 transition-opacity delay-75"
					>
						{project.name}
					</span>
				</Card>
			{/each}
		{:else}
			{#each Array(6) as _, i (i)}
				<Loader class="aspect-video w-full md:w-[calc(25%-1rem)]"></Loader>
			{/each}
		{/if}
	</div>
</div>
