// src/routes/admin/experiences.tsx
import Modal from "@/components/widgets/modal"
import type { experiencesInterface } from "@/interface"
import { get } from "@/lib/api"
import { use, useState } from "react"

const getExperience = get("experiences")

export default function AdminExperiences() {
  const experiences = use(getExperience) as { data: experiencesInterface[] }

  const [visible, setVisible] = useState(false)
  const [modify, setModify] = useState<experiencesInterface | null>(null)

  function updateExperience() {
    console.log(modify)
  }

  return (
    <div className="flex flex-col min-h-full gap-2">
      {
        experiences.data.length > 0 ?
          experiences.data.reverse().map((exp: experiencesInterface, i: number) => {
            return (
              <div
                onClick={() => {
                  setVisible(true)
                  setModify(exp)
                }}
                key={`${i}. ${exp.title}`}
                className="bg-card rounded p-2 w-full">
                <span>{exp.title} [{exp.year}]</span>
                <ul className="px-2">
                  {
                    exp.content.length > 0 ?
                      exp.content.map((content: string, j: number) => {
                        return (
                          <li
                            className="flex items-center gap-2"
                            key={`${j}`}>
                            <span className="text-[0.75rem]">&gt;</span> {content}
                          </li>
                        )
                      })
                      : null}
                </ul>
              </div>
            )
          })
          : <div>No Experience here</div>
      }
      <Modal setVisible={setVisible} visible={visible} className="p-3 gap-3 rounded max-h-3/4 w-2/3 overflow-hidden">
        <div className="flex justify-center w-full">
          <span className="silk text-xl">Edit Experience information</span>
        </div>
        {
          modify ?
            <form onSubmit={updateExperience} className="flex flex-col gap-2 overflow-hidden">
              <span className="flex flex-col">
                <label
                  htmlFor="title"
                  className="px-3 text-[0.75rem]">Title</label>
                <input
                  className="bg-input p-2 rounded"
                  id="title"
                  value={modify.title}
                  onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
                    setModify({
                      ...modify,
                      "title": e.target.value
                    })
                  }}
                  type="text" />
              </span>
              <span className="flex flex-col">
                <label
                  htmlFor="year"
                  className="px-3 text-[0.75rem]">Year</label>
                <input
                  className="bg-input p-2 rounded"
                  id="year"
                  value={modify.year}
                  onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
                    setModify({
                      ...modify,
                      "year": parseInt(e.target.value)
                    })
                  }}
                  type="number" />
              </span>
              <span className="flex flex-col flex-1 overflow-hidden">
                <span
                  className="px-3 text-[0.75rem]">Contents</span>
                <div className="flex flex-col gap-2 overflow-y-auto h-full">
                  {
                    modify.content.map((c: string, k: number) => {
                      return (
                        <span
                          className="w-full flex bg-input p-2 rounded"
                          key={`${k}. ${c}`}>
                          <input
                            className="flex-1 outline-none"
                            value={c}
                            type="text" />
                          <span
                            className="cursor-pointer p-2 font-extrabold text-red-500 hover:text-red-800"
                            onClick={() => {
                              const content = modify.content.filter((_, i) => i !== k)
                              setModify({
                                ...modify,
                                "content": content
                              })
                            }}>X</span>
                        </span>
                      )
                    })
                  }
                </div>
              </span>
              <div className="flex w-full p-1 gap-3">
                <input type="button" className="flex-1 card p-1" value="Add Content" />
                <input className="flex-1 card p-1" type="submit" value="Update Experience" />
              </div>
            </form>
            : null
        }
      </Modal>
    </div>
  )
}

// src/routes/admin/experiences.svelte
<script lang="ts">
	import { onMount } from "svelte";
	import { adminPut, get } from "@/lib/fetch";
	import toast from "svelte-french-toast";

	type Experience = {
		title: string;
		year: number;
		icon: string;
		content: string[];
	};

	let experiences: Experience[] = $state([]);
	let code: string = $state("");

	let form: Experience = $state({
		title: "",
		year: new Date().getFullYear(),
		icon: "",
		content: [""],
	});

	let editing: boolean = $state(false);
	let editIndex: number | null = $state(null);
	let sending: boolean = $state(false);

	function addContentField() {
		form.content = [...form.content, ""];
	}

	function removeContentField(index: number) {
		form.content = form.content.filter((_, i) => i !== index);
	}

	async function saveExperience() {
		console.log("Sending");
		if (!form.title.trim()) return;

		if (editing && editIndex !== null) {
			sending = true;
			// TODO: To update a certain index
			experiences[editIndex] = form;
			experiences.reverse();

			const expResponse = await adminPut("experiences", code, experiences);
			if (expResponse.error) {
				toast(expResponse.error, {
					position: "bottom-right",
				});
				sending = false;
				experiences.reverse();
				return;
			}
			toast("Updated", {
				position: "bottom-right",
			});
			sending = false;
			experiences.reverse();
		}
		resetForm();
	}

	function editExperience(index: number) {
		const exp = experiences[index];
		form = { ...exp };
		editIndex = index;
	}

	function resetForm() {
		const currentYear = new Date().getFullYear();
		const current: Experience[] = experiences.filter((exp: Experience) => {
			return exp.year == currentYear;
		});

		if (current.length > 0) {
			form = current[0];
			editing = true;
			editIndex = 0;
		} else {
			form = {
				title: "",
				year: new Date().getFullYear(),
				icon: "",
				content: [""],
			};
			editing = false;
			editIndex = null;
		}
	}

	onMount(async () => {
		const { data } = await get("experiences");
		experiences = data.reverse();

		const currentYear = new Date().getFullYear();
		const current: Experience[] = experiences.filter((exp: Experience) => {
			return exp.year == currentYear;
		});

		if (current.length > 0) {
			form = current[0];
			editing = true;
			editIndex = 0;
		}
	});
</script>

<div class="h-full text-zinc-900 dark:bg-zinc-950 dark:text-zinc-50 p-6 pt-20">
	<div class="flex w-full h-full gap-6">
		<div
			class="h-full w-[calc(50%-1rem)] rounded-2xl border border-zinc-800 dark:bg-zinc-900 p-5 overflow-hidden"
		>
			<h2 class="mb-5 text-2xl font-bold">
				{editing && editIndex !== null ? "Update Experience" : "Add Experience"}
			</h2>

			<div class="flex-1 max-h-[calc(90%-0.5rem)] space-y-4 overflow-y-auto">
				<div>
					<label class="mb-2 block text-sm text-zinc-500"> Title </label>

					<input
						bind:value={form.title}
						type="text"
						placeholder="Beginner's Path"
						class="w-full rounded-xl border border-zinc-700 dark:bg-zinc-800 px-4 py-3 outline-none transition focus:border-zinc-500"
					/>
				</div>

				<div class="flex flex-row w-full gap-5">
					<div class="flex-1">
						<label class="mb-2 block text-sm text-zinc-500"> Year </label>

						<input
							bind:value={form.year}
							type="number"
							disabled={true}
							class="w-full rounded-xl border border-zinc-700 dark:bg-zinc-800 px-4 py-3 outline-none transition focus:border-zinc-500"
						/>
					</div>

					<div class="flex-1">
						<label class="mb-2 block text-sm text-zinc-500"> Admin Code </label>

						<input
							bind:value={code}
							type="password"
							class="w-full rounded-xl border border-zinc-700 dark:bg-zinc-800 px-4 py-3 outline-none transition focus:border-zinc-500"
						/>
					</div>
				</div>

				<div>
					<label class="mb-2 block text-sm text-zinc-500">
						Font Awesome Icon
					</label>

					<input
						bind:value={form.icon}
						type="text"
						placeholder="fa-solid fa-hourglass"
						class="w-full rounded-xl border border-zinc-700 dark:bg-zinc-800 px-4 py-3 outline-none transition focus:border-zinc-500"
					/>
				</div>

				<div>
					<div class="mb-3 flex items-center justify-between">
						<label class="text-sm text-zinc-500"> Content </label>

						<button
							onclick={addContentField}
							type="button"
							class="rounded-lg bg-zinc-200 dark:bg-zinc-800 px-3 py-1 text-sm font-medium text-zinc-950 dark:text-zinc-50"
						>
							Add
						</button>
					</div>

					<div class="space-y-3">
						{#each form.content as item, index}
							<div class="flex gap-2">
								<input
									bind:value={form.content[index]}
									type="text"
									placeholder="Experience detail..."
									class="flex-1 rounded-xl border border-zinc-700 dark:bg-zinc-800 px-4 py-3 outline-none transition focus:border-zinc-500"
								/>

								<button
									onclick={() => removeContentField(index)}
									type="button"
									class="rounded-xl bg-red-500/20 px-4 text-red-400"
								>
									✕
								</button>
							</div>
						{/each}
					</div>
				</div>

				<div class="flex gap-3 pt-3">
					<button
						disabled={sending}
						onclick={saveExperience}
						class="flex-1 rounded-xl bg-zinc-500 py-3 font-semibold text-zinc-800 dark:text-zinc-200 transition hover:bg-zinc-400"
					>
						{editing && editIndex !== null ? "Update" : "Save"}
					</button>

					<button
						disabled={sending}
						onclick={resetForm}
						type="button"
						class="rounded-xl border border-zinc-700 px-5"
					>
						Reset
					</button>
				</div>
			</div>
		</div>

		<div class="flex flex-col w-[calc(50%-1rem)] h-full overflow-y-auto gap-5">
			{#each experiences as exp, index}
				<div
					class="rounded-2xl border border-zinc-800 dark:bg-zinc-900 p-5 transition hover:border-zinc-500 w-full transition-all delay-75 ease-in-out"
				>
					<div class="mb-4 flex items-start justify-between">
						<div class="flex items-center gap-4">
							<div
								class="flex h-14 w-14 items-center justify-center rounded-2xl bg-zinc-200 dark:bg-zinc-700 text-2xl text-zinc-400"
							>
								<i class={exp.icon}></i>
							</div>

							<div>
								<h3 class="text-xl font-bold">
									{exp.title}
								</h3>

								<p class="text-sm text-zinc-500">
									{exp.year}
								</p>
							</div>
						</div>

						<div class="flex gap-2">
							<button
								disabled={sending}
								onclick={() => editExperience(index)}
								class="rounded-lg bg-yellow-500/75 dark:bg-yellow-500/50 px-4 py-2 text-sm text-yellow-900 dark:text-yellow-200 transition hover:bg-yellow-500/20"
							>
								Edit
							</button>
						</div>
					</div>

					<ul class="space-y-2">
						{#each exp.content as item}
							<li
								class="flex items-start gap-3 text-zinc-700 dark:text-zinc-300"
							>
								<div class="mt-2 h-2 w-2 rounded-full bg-zinc-500"></div>
								<span>{item}</span>
							</li>
						{/each}
					</ul>
				</div>
			{/each}
		</div>
	</div>
</div>
