// src/pages/admin/experiences.tsx
import { ChangeEvent, useEffect, useState } from "react";
import { experience } from "../../utils/interfaces";
import { adminPut, get } from "../../utils/api";
import Input from "../../widgets/input";
import { ToastContainer, toast } from "react-toastify";

export default function Experiences() {
  const [exp, setExp] = useState<experience[]>([]);
  const [index, setIndex] = useState(-1);
  const [mexp, setMexp] = useState<experience>({
    title: "",
    year: 0,
    icon: "",
    content: [],
  });
  const [sending, setSending] = useState(false);
  const [code, setCode] = useState({ code: "" });

  useEffect(() => {
    (async () => {
      const data = await get("experiences");
      if (data.message) {
        setExp(data.data);
      }
    })();
  }, []);

  const submitExp = async () => {
    setSending(true);
    const experiences: experience[] = exp;
    experiences[index] = mexp;
    const response = await adminPut("experiences", code.code, experiences);
    if (response.message) {
      setIndex(-1);
      toast("Data Updated successfully");
    } else {
      toast("Didn't update");
    }
    setSending(false);
  };

  return (
    <div className="flex flex-col gap-2 w-full h-full">
      <h1 className="text-center text-xl">Update Experiences</h1>
      <div className="flex flex-col md:flex-row w-full p-5 gap-5 h-full">
        <div className="flex flex-col gap-1 min-w-1/3 overflow-y-scroll overflow-x-hidden h-full">
          {exp.map((xp: experience, i: number) => {
            return (
              <span
                onClick={() => {
                  setMexp(xp);
                  setIndex(i);
                }}
                className={`flex flex-row justify-between p-2 gap-2 rounded cursor-pointer ${i === index ? "bg-slate-950 text-white" : ""}`}
              >
                <span>{xp.title}</span>
                <span>{xp.year}</span>
              </span>
            );
          })}
        </div>
        <div
          className={`flex flex-col gap-2 h-full ${index >= 0 ? "w-full" : "hidden"}`}
        >
          <Input value={mexp} name="title" onChange={setMexp}>
            Title
          </Input>
          <Input value={mexp} name="year" onChange={setMexp}>
            Year
          </Input>
          <Input value={mexp} name="icon" onChange={setMexp}>
            Icon
          </Input>
          <Input type="password" value={code} onChange={setCode} name="code">
            Code
          </Input>
          <div className="flex flex-col border border-solid h-full border-[#0c0c0c] dark:border-[#f9f9f6] w-full gap-2 rounded-sm">
            <span className="pl-4">Content</span>
            <textarea
              className="w-full border-none outline-none px-2 h-full resize-none"
              name=""
              id=""
              value={mexp?.content?.join("\n")}
              onChange={(event: ChangeEvent<HTMLTextAreaElement>) => {
                setMexp((prev) => ({
                  ...prev,
                  content: event.target.value.split("\n"),
                }));
              }}
            ></textarea>
          </div>
          <button
            disabled={sending}
            onClick={submitExp}
            className="flex flex-col border border-solid border-[#0c0c0c] dark:border-[#f9f9f6] w-full p-3 rounded-sm"
          >
            {sending ? "Please Wait" : "Submit"}
          </button>
        </div>
      </div>
      <ToastContainer />
    </div>
  );
}

// src/routes/admin/experiences.svelte
<script lang="ts">
	import { onMount } from "svelte";
	import { adminPut, get } from "@/lib/fetch";
	import toast from "svelte-french-toast";

	type Experience = {
		title: string;
		year: number;
		icon: string;
		content: string[];
	};

	let experiences: Experience[] = $state([]);
	let code: string = $state("");

	let form: Experience = $state({
		title: "",
		year: new Date().getFullYear(),
		icon: "",
		content: [""],
	});

	let editing: boolean = $state(false);
	let editIndex: number | null = $state(null);
	let sending: boolean = $state(false);

	function addContentField() {
		form.content = [...form.content, ""];
	}

	function removeContentField(index: number) {
		form.content = form.content.filter((_, i) => i !== index);
	}

	async function saveExperience() {
		console.log("Sending");
		if (!form.title.trim()) return;

		if (editing && editIndex !== null) {
			sending = true;
			// TODO: To update a certain index
			experiences[editIndex] = form;
			experiences.reverse();

			const expResponse = await adminPut("experiences", code, experiences);
			if (expResponse.error) {
				toast(expResponse.error, {
					position: "bottom-right",
				});
				sending = false;
				experiences.reverse();
				return;
			}
			toast("Updated", {
				position: "bottom-right",
			});
			sending = false;
			experiences.reverse();
		}
		resetForm();
	}

	function editExperience(index: number) {
		const exp = experiences[index];
		form = { ...exp };
		editIndex = index;
	}

	function resetForm() {
		const currentYear = new Date().getFullYear();
		const current: Experience[] = experiences.filter((exp: Experience) => {
			return exp.year == currentYear;
		});

		if (current.length > 0) {
			form = current[0];
			editing = true;
			editIndex = 0;
		} else {
			form = {
				title: "",
				year: new Date().getFullYear(),
				icon: "",
				content: [""],
			};
			editing = false;
			editIndex = null;
		}
	}

	onMount(async () => {
		const { data } = await get("experiences");
		experiences = data.reverse();

		const currentYear = new Date().getFullYear();
		const current: Experience[] = experiences.filter((exp: Experience) => {
			return exp.year == currentYear;
		});

		if (current.length > 0) {
			form = current[0];
			editing = true;
			editIndex = 0;
		}
	});
</script>

<div class="h-full text-zinc-900 dark:bg-zinc-950 dark:text-zinc-50 p-6 pt-20">
	<div class="flex w-full h-full gap-6">
		<div
			class="h-full w-[calc(50%-1rem)] rounded-2xl border border-zinc-800 dark:bg-zinc-900 p-5 overflow-hidden"
		>
			<h2 class="mb-5 text-2xl font-bold">
				{editing && editIndex !== null ? "Update Experience" : "Add Experience"}
			</h2>

			<div class="flex-1 max-h-[calc(90%-0.5rem)] space-y-4 overflow-y-auto">
				<div>
					<label class="mb-2 block text-sm text-zinc-500"> Title </label>

					<input
						bind:value={form.title}
						type="text"
						placeholder="Beginner's Path"
						class="w-full rounded-xl border border-zinc-700 dark:bg-zinc-800 px-4 py-3 outline-none transition focus:border-zinc-500"
					/>
				</div>

				<div class="flex flex-row w-full gap-5">
					<div class="flex-1">
						<label class="mb-2 block text-sm text-zinc-500"> Year </label>

						<input
							bind:value={form.year}
							type="number"
							disabled={true}
							class="w-full rounded-xl border border-zinc-700 dark:bg-zinc-800 px-4 py-3 outline-none transition focus:border-zinc-500"
						/>
					</div>

					<div class="flex-1">
						<label class="mb-2 block text-sm text-zinc-500"> Admin Code </label>

						<input
							bind:value={code}
							type="password"
							class="w-full rounded-xl border border-zinc-700 dark:bg-zinc-800 px-4 py-3 outline-none transition focus:border-zinc-500"
						/>
					</div>
				</div>

				<div>
					<label class="mb-2 block text-sm text-zinc-500">
						Font Awesome Icon
					</label>

					<input
						bind:value={form.icon}
						type="text"
						placeholder="fa-solid fa-hourglass"
						class="w-full rounded-xl border border-zinc-700 dark:bg-zinc-800 px-4 py-3 outline-none transition focus:border-zinc-500"
					/>
				</div>

				<div>
					<div class="mb-3 flex items-center justify-between">
						<label class="text-sm text-zinc-500"> Content </label>

						<button
							onclick={addContentField}
							type="button"
							class="rounded-lg bg-zinc-200 dark:bg-zinc-800 px-3 py-1 text-sm font-medium text-zinc-950 dark:text-zinc-50"
						>
							Add
						</button>
					</div>

					<div class="space-y-3">
						{#each form.content as item, index}
							<div class="flex gap-2">
								<input
									bind:value={form.content[index]}
									type="text"
									placeholder="Experience detail..."
									class="flex-1 rounded-xl border border-zinc-700 dark:bg-zinc-800 px-4 py-3 outline-none transition focus:border-zinc-500"
								/>

								<button
									onclick={() => removeContentField(index)}
									type="button"
									class="rounded-xl bg-red-500/20 px-4 text-red-400"
								>
									✕
								</button>
							</div>
						{/each}
					</div>
				</div>

				<div class="flex gap-3 pt-3">
					<button
						disabled={sending}
						onclick={saveExperience}
						class="flex-1 rounded-xl bg-zinc-500 py-3 font-semibold text-zinc-800 dark:text-zinc-200 transition hover:bg-zinc-400"
					>
						{editing && editIndex !== null ? "Update" : "Save"}
					</button>

					<button
						disabled={sending}
						onclick={resetForm}
						type="button"
						class="rounded-xl border border-zinc-700 px-5"
					>
						Reset
					</button>
				</div>
			</div>
		</div>

		<div class="flex flex-col w-[calc(50%-1rem)] h-full overflow-y-auto gap-5">
			{#each experiences as exp, index}
				<div
					class="rounded-2xl border border-zinc-800 dark:bg-zinc-900 p-5 transition hover:border-zinc-500 w-full transition-all delay-75 ease-in-out"
				>
					<div class="mb-4 flex items-start justify-between">
						<div class="flex items-center gap-4">
							<div
								class="flex h-14 w-14 items-center justify-center rounded-2xl bg-zinc-200 dark:bg-zinc-700 text-2xl text-zinc-400"
							>
								<i class={exp.icon}></i>
							</div>

							<div>
								<h3 class="text-xl font-bold">
									{exp.title}
								</h3>

								<p class="text-sm text-zinc-500">
									{exp.year}
								</p>
							</div>
						</div>

						<div class="flex gap-2">
							<button
								disabled={sending}
								onclick={() => editExperience(index)}
								class="rounded-lg bg-yellow-500/75 dark:bg-yellow-500/50 px-4 py-2 text-sm text-yellow-900 dark:text-yellow-200 transition hover:bg-yellow-500/20"
							>
								Edit
							</button>
						</div>
					</div>

					<ul class="space-y-2">
						{#each exp.content as item}
							<li
								class="flex items-start gap-3 text-zinc-700 dark:text-zinc-300"
							>
								<div class="mt-2 h-2 w-2 rounded-full bg-zinc-500"></div>
								<span>{item}</span>
							</li>
						{/each}
					</ul>
				</div>
			{/each}
		</div>
	</div>
</div>
