// src/routes/home/projects.svelte
<script lang="ts">
	import { retrieval } from "@/lib/fetch.ts";
	import Loader from "@/components/loader.svelte";
	import Card from "@/components/card.svelte";

	export let categories: string[] = ["all"];
	export let totalProjects: Record<string, any>[] = [];
	export let projects: Record<string, any>[] = [];
	let active = "all";

	function filter(category: string) {
		active = category.toLowerCase();
		projects = totalProjects.filter((proj: Record<string, any>) =>
			active === "all" ? true : proj.category.includes(active.toLowerCase()),
		);
	}
</script>

<div
	id="projects"
	class="flex flex-col p-2 pt-[25%] md:pt-[10%] h-full w-full overflow-y-auto snap-start"
>
	<div
		class="flex gap-2 items-center md:justify-center my-5 py-3 overflow-x-auto"
	>
		{#each categories as category}
			<li
				onclick={() => {
					filter(category);
				}}
				class={`select-none cursor-pointer ${active === category.toLowerCase() ? "border border-black dark:border-white border-solid" : "bg-[#f0f8ff] dark:bg-[#313131]"} px-2 rounded list-none text-[0.80em]`}
			>
				{#if category.length <= 3 && category !== "all"}
					{category.toUpperCase()}
				{:else}
					{category[0].toUpperCase()}{category.substring(1)}
				{/if}
			</li>
		{/each}
	</div>
	<div class="flex flex-wrap w-full gap-5 p-5">
		{#if projects.length > 0}
			{#each projects as project}
				{#if active.toLowerCase() === "all" && project.img}
					<Card
						class_="relative aspect-video w-full md:w-[calc(33.333%-1rem)] rounded overflow-hidden !p-0 group"
					>
						<img
							class="absolute w-full h-full md:grayscale group-hover:grayscale-0"
							src={retrieval("retrieve", { file: project.img ?? "" })}
							alt=""
						/>
						<span
							class="absolute z-1 bottom-0 left-0 right-0 bg-[#212121]/50 p-2 md:opacity-0 group-hover:opacity-100 transition-opacity delay-75"
						>
							{project.name}
						</span>
					</Card>
				{:else if active.toLowerCase() !== "all"}
					<Card
						class_="relative aspect-video w-full md:w-[calc(33.333%-1rem)] rounded overflow-hidden !p-0 group"
					>
						<img
							class="absolute w-full h-full md:grayscale group-hover:grayscale-0"
							src={retrieval("retrieve", { file: project.img ?? "" })}
							alt=""
						/>
						<span
							class="absolute z-1 bottom-0 left-0 right-0 bg-[#212121]/50 p-2 md:opacity-0 group-hover:opacity-100 transition-opacity delay-75"
						>
							{project.name}
						</span>
					</Card>
				{/if}
			{/each}
		{:else}
			{#each Array(6) as _, i (i)}
				<Loader class_="aspect-video w-full md:w-[calc(33.333%-1rem)]"></Loader>
			{/each}
		{/if}
	</div>
</div>

// src/screen/projects.tsx
import { pages_interface, projects } from "../utils/interfaces";
import { get } from "../utils/api";
import { useEffect, useState } from "react";

export default function Projects(props: pages_interface) {
  const [categories, setCategories] = useState<string[]>([]);
  const [listProjects, setListProjects] = useState<projects[]>([]);
  const [projects, setProjects] = useState<projects[]>([]);
  const [category, setCategory] = useState("all");

  useEffect(() => {
    (async () => {
      const api = await get("projects");
      setCategories(["all", ...api.categories]);
      const programs = api.projects.sort((a: projects, b: projects) =>
        a.name.localeCompare(b.name),
      );
      setListProjects(programs);
      if (category && category !== "all") {
        setProjects(
          programs.filter((program: projects) =>
            program.category.includes(category.toLowerCase()),
          ),
        );
      } else {
        setProjects(programs);
      }
    })();
  }, []);

  useEffect(() => {
    if (category && category !== "all") {
      setProjects(
        listProjects.filter((project) =>
          project.category.includes(category.toLowerCase()),
        ),
      );
    } else {
      setProjects(listProjects);
    }
  }, [category]);

  return (
    <div
      id={props.id}
      className={`flex flex-col ${props.className} gap-1 w-full h-full py-2`}
    >
      <h1 className="text-base lg:text-2xl">
        {category[0].toUpperCase() + category.substring(1).toLowerCase()}{" "}
        Projects
      </h1>
      <div className="flex w-full gap-2 box-border overflow-x-auto overflow-y-hidden p-2">
        {categories.map((category_) => {
          return (
            <span
              onClick={() => {
                setCategory(category_.toLowerCase());
              }}
              className={`${category_ === category ? "bg-transparent border border-solid border-black dark:border-[#f8f8ff]" : "border border-solid border-transparent bg-[#e1e2e3] dark:bg-[#1d1f21]"} w-full text-center select-none px-2 rounded-md cursor-pointer`}
            >
              {category_[0].toUpperCase() + category_.substring(1)}
            </span>
          );
        })}
      </div>
      <div className="flex flex-wrap justify-center gap-4 w-full h-full box-border overflow-y-auto pb-4">
        {listProjects.length > 0 ? (
          projects.length <= 0 ? (
            <p>
              No Projects included with "
              {category[0].toUpperCase() + category.substring(1).toLowerCase()}"
              yet.
            </p>
          ) : (
            projects.map((item) => {
              return (
                <div
                  onClick={() => {
                    const w = window.open(item.link);
                    if (w) w.focus();
                  }}
                  style={{
                    backgroundImage: `url(${item.src ?? ""})`,
                  }}
                  className={`flex flex-col justify-end h-1/3 w-3/7 md:w-2/7 bg-[#212121] text-white p-2 lg:grayscale hover:grayscale-0 bg-center bg-cover bg-no-repeat box-border overflow-hidden rounded transition ease-all delay-150`}
                >
                  {/* <img */}
                  {/*   className="grayscale hover:grayscale-0 transition ease-all delay-150 w-full aspect-video" */}
                  {/*   alt={item.name} */}
                  {/*   src={item.src} */}
                  {/* /> */}
                  <span className="flex flex-col bg-[#212121]/50 select-none cursor-pointer hover:underline justify-center items-center box-border">
                    <h1 className="text-base md:text-xl text-center">
                      {item.name}
                    </h1>
                    <h3 className="text-xs text-center">
                      {item.description ?? "No description applied"}
                    </h3>
                  </span>
                </div>
              );
            })
          )
        ) : (
          <div className="flex flex-col h-full w-full items-center justify-center">
            <p className="text-[2rem]">Please wait for a moment</p>
            <p className="text-[1.25rem]">Backend is currently loading</p>
          </div>
        )}
      </div>
    </div>
  );
}
