// src/routes/user/certificates.svelte
<script lang="ts">
	import Card from "@/components/card.svelte"
	import HomeButton from "@/components/home-button.svelte"
	import { get } from "@/lib/fetch.ts"
	import { onMount } from  "svelte"
	import { Toaster, toast } from "svelte-french-toast"

	let certs = []
	let pages = 1
	let page = 1
	
	onMount(async () => {
		const api = await get("certs", {
			limit: 6,
			page: page
		})
		if(api.error){
			toast.error(api.error, {
				position: "bottom-right"
			})
		}else{
			certs = api.data
			pages = api.pages
		}
	})

	async function changepage(p: number) {
		page = p;
		const data = await get("certs", {
			page: page,
			limit: 6,
		});
		pages = data.pages;
		certs = data.data;
	}

</script>

<div
	class="flex flex-wrap p-2 w-full h-full gap-2 overflow-hidden overflow-y-auto snap-start pt-[5%]"
>
	<HomeButton title="Certificates" description="Lists of Ryann Kim's certifications" past="/" />
	<div class="flex flex-wrap gap-5 py-[2%] p-5">
		{#each certs as cert}
			<Card
				class_="flex flex-wrap aspect-video w-full md:w-[calc(33.333%-1rem)] rounded !p-0"
				>
				<img class="h-full w-full" src={cert.url} alt={cert.source} />
			</Card>
		{/each}
	</div>
	<div class="flex fixed z-10 bottom-0 left-0 right-0 justify-center p-4">
		<div
			class="flex gap-2 bg-[#f0f8ff]/75 dark:bg-[#121212]/75 shadow shadow-[#252525] backdrop-blur-xs rounded-full p-2 px-5"
		>
			<span
				class="cursor-pointer select-none flex items-center justify-center"
				onclick={() => {
					changepage(page > 1 ? page - 1 : 1);
				}}>Prev</span
			>
			{#each Array(pages) as _, p}
				<span
					onclick={() => {
						changepage(p + 1);
					}}
					class={`${p + 1 === page ? "dark:bg-[#555555]" : ""} flex items-center justify-center text-center rounded-full aspect-square w-7 h-7 cursor-pointer select-none`}
				>
					{p + 1}
				</span>
			{/each}
			<span
				class="cursor-pointer select-none flex items-center justify-center"
				onclick={() => {
					changepage(page < pages ? page + 1 : pages);
				}}>Next</span
			>
		</div>
	</div>
	<Toaster />
</div>

// src/pages/user/certificates.tsx
import { useEffect, useState } from "react";
import { certificates } from "../../utils/interfaces";
import { get, retrieval } from "../../utils/api";
import { toast, ToastContainer } from "react-toastify";
import { useNavigate } from "react-router";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faLongArrowLeft } from "@fortawesome/free-solid-svg-icons";
import Card from "../../components/card";

const isUrl = (url: string) => {
  if (url.startsWith("http")) {
    return url;
  }
  retrieval("retrieve", {
    file: url,
  });
};

export default function Certis() {
  const [certList, setCerts] = useState<certificates[]>([]);
  const [page, setPage] = useState(1);
  const [pages, setPages] = useState<number>(0);
  const navigate = useNavigate();

  useEffect(() => {
    (async () => {
      const certs = await get("certs", {
        limit: 12,
        page: page,
      });
      if (certs.error) {
        toast(certs.error);
        return;
      }
      setPages(certs.pages);
      setCerts(certs.data);
    })();
  }, []);

  useEffect(() => {
    (async () => {
      const certs = await get("certs", {
        limit: 12,
        page: page,
      });
      if (certs.error) {
        toast(certs.error);
        return;
      }
      setCerts(certs.data);
    })();
  }, [page]);

  return (
    <div className="flex flex-col w-full h-full select-none">
      <div className="flex flex-col justify-center w-full gap-3 border-b border-b-black dark:border-b-white border-b-solid px-3 py-2">
        <div className="flex">
          <div
            onClick={() => navigate("/")}
            className="flex w-full items-center gap-2 cursor-pointer"
          >
            <FontAwesomeIcon icon={faLongArrowLeft} />
            <h1 className="text-[1.5rem] underline">Lists of Certifications</h1>
          </div>
        </div>
        <span className="text-sm">Page: {page}</span>
      </div>
      <div className="flex flex-wrap gap-2 overflow-y-auto p-2 pb-15">
        {certList.map((cert) => {
          return (
            <Card className="relative w-full md:w-[calc(33.333%-0.5rem)] aspect-video group rounded">
              <img
                className="absolute w-full h-full"
                src={isUrl(cert.url)}
                alt={cert.source}
              />
              <div className="flex flex-col absolute z-1 md:opacity-0 group-hover:opacity-100 transition-opacity justify-end h-full w-full">
                <span className="flex justify-between w-full bg-black/50 text-white py-2 px-2">
                  <span>{cert.source}</span>
                  <span>[{cert.category}]</span>
                </span>
              </div>
            </Card>
          );
        })}
      </div>
      <div className="flex left-0 right-0 bottom-0 fixed items-center z-10 justify-center p-2">
        <div className="flex justify-center bg-slate-300/50 backdrop-blur-sm px-10 py-1 gap-3 rounded">
          <p
            className={`flex p-1 rounded aspect-square h-8 items-center justify-center cursor-pointer`}
            onClick={() => {
              if (page > 1) {
                setPage((prev) => prev - 1);
              } else {
                setPage(1);
              }
            }}
          >
            Prev
          </p>
          {pages > 1 &&
            Array.from({ length: pages }).map((_, index) => {
              return (
                <p
                  className={`flex ${index === page - 1 ? "bg-slate-950/50 text-white " : ""} p-1 rounded aspect-square h-8 items-center justify-center cursor-pointer`}
                  onClick={() => {
                    setPage(index + 1);
                  }}
                >
                  {index + 1}
                </p>
              );
            })}
          <p
            className={`flex p-1 rounded aspect-square h-8 items-center justify-center cursor-pointer`}
            onClick={() => {
              if (page < pages) {
                setPage((prev) => prev + 1);
              } else {
                setPage(pages);
              }
            }}
          >
            Next
          </p>
        </div>
      </div>
      <ToastContainer />
    </div>
  );
}
