// src/parts/header.tsx
import { useEffect, useState } from "react";
import { default_interface, link_interface } from "./../utils/interfaces.tsx";
import {
  faContactCard,
  faFolderOpen,
  faUser,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

import Logo from "./../assets/logo.jpg";

function onclick(id: string) {
  const _ = document.getElementById(id);
  if (_) {
    _.scrollIntoView({
      behavior: "smooth",
    });
  }
}

function List(props: link_interface) {
  return (
    <li
      onClick={() => {
        onclick(props.link);
      }}
      className="cursor-pointer p-2 link-animation"
    >
      <FontAwesomeIcon className="lg:hidden" icon={props.icon} />
      {/* <span className="hidden lg:inline">{props.children}</span> */}
    </li>
  );
}

export default function Header(props: default_interface) {
  const [scrolled, setScrolled] = useState(false);

  useEffect(() => {
    const base = document.getElementById("base");
    if (base) {
      const scrollEffect = () => {
        if (base.scrollTop > 250) {
          setScrolled(true);
        } else {
          setScrolled(false);
        }
      };

      base.addEventListener("scroll", scrollEffect);
      return () => {
        base.removeEventListener("scroll", scrollEffect);
      };
    }
  }, []);

  return (
    <header
      className={`flex flex-row w-full sticky justify-between items-center p-2 select-none dark:text-white text-black ${scrolled ? "h-12 lg:h-16" : "h-16 lg:h-20 lg:text-lg"} ${props.className} transition ease-in delay-150`}
    >
      <img
        onClick={() => {
          onclick("home");
        }}
        src={Logo}
        className="h-[50px] rounded-full aspect-square"
      />
      <nav className="flex flex-row list-none">
        {/* <List link="home" icon={faHouse}> */}
        {/*   {/* Home *} */}
        {/* </List> */}
        <List link="about" icon={faUser}>
          About
        </List>
        <List link="projects" icon={faFolderOpen}>
          Projects
        </List>
        <List link="contact" icon={faContactCard}>
          Contact
        </List>
      </nav>
    </header>
  );
}

// src/components/header.svelte
<script lang="ts">
	import Logo from "@/assets/logo.png";
	import Icon from "@/components/icon.svelte";

	export let scroll: number = 0;
	function scrollme(id: string) {
		const p = document.getElementById(id);
		if (p) {
			p.scrollIntoView({
				behavior: "smooth",
			});
		}
	}
</script>

<div
	class="flex items-center justify-center py-4 fixed top-[0.25rem] w-full z-10 select-none"
>
	<nav
		class="flex flex-row items-center gap-3 p-2 bg-[#252525] rounded-full px-8"
	>
		<img
			onclick={() => {
				scrollme("hero");
			}}
			src={Logo}
			alt="logo"
			class={`aspect-square w-5`}
		/>
		<ul class="flex items-center gap-2">
			<li
				onclick={() => {
					scrollme("about");
				}}
				class="cursor-pointer"
			>
				<Icon icon="fa-user" name="About" selected={scroll === 1} />
			</li>
			<li
				onclick={() => {
					scrollme("projects");
				}}
				class="cursor-pointer"
			>
				<Icon icon="fa-folder-open" name="Projects" selected={scroll === 2} />
			</li>
			<li
				onclick={() => {
					scrollme("blogs");
				}}
				class="cursor-pointer"
			>
				<Icon
					icon="fa-rss"
					type="fa-solid"
					name="Blogs"
					selected={scroll === 3}
				/>
			</li>
			<li
				onclick={() => {
					scrollme("contact");
				}}
				class="cursor-pointer"
			>
				<Icon icon="fa-address-card" name="Contact" selected={scroll === 4} />
			</li>
		</ul>
	</nav>
</div>
