// src/pages/user/blogs.tsx
import { useEffect, useState } from "react";
import { blogs } from "../../utils/interfaces";
import { get } from "../../utils/api";
import { toast, ToastContainer } from "react-toastify";
import { Link, useNavigate } from "react-router";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faLongArrowLeft } from "@fortawesome/free-solid-svg-icons";

export default function Blogs() {
  const [blogList, setBlogs] = useState<blogs[]>([]);
  const [page, setPage] = useState(1);
  const [pages, setPages] = useState<number>(0);
  const navigate = useNavigate();

  useEffect(() => {
    (async () => {
      const blog = await get("blog", {
        limit: 12,
        page: page,
      });
      if (blog.error) {
        toast(blog.error);
        return;
      }
      setPages(blog.pages);
      setBlogs(blog.data);
    })();
  }, []);

  useEffect(() => {
    (async () => {
      const blog = await get("blog", {
        limit: 12,
        page: page,
      });
      if (blog.error) {
        toast(blog.error);
        return;
      }
      setBlogs(blog.data);
    })();
  }, [page]);

  return (
    <div className="flex flex-col w-full h-full select-none">
      <div className="flex flex-col justify-center w-full gap-3 border-b border-b-black dark:border-b-white border-b-solid px-3 py-2">
        <div className="flex">
          <div
            onClick={() => navigate("/")}
            className="flex w-full items-center gap-2 cursor-pointer"
          >
            <FontAwesomeIcon icon={faLongArrowLeft} />
            <h1 className="text-[1.5rem] underline">Blog lists Page</h1>
          </div>
        </div>
        <span className="text-sm">Page: {page}</span>
      </div>
      <div className="flex flex-col md:grid md:grid-cols-3 gap-2 overflow-y-auto p-2">
        {blogList.map((blog) => {
          return (
            <Link to={`${blog.id}`} className="w-full aspect-video">
              <div className="flex flex-col bg-zinc-200 shadow-sm shadow-black text-black dark:bg-slate-900 dark:border dark:border-slate-500 dark:border-solid dark:text-white p-4 rounded-lg w-full h-full overflow-hidden gap-1">
                <span>{blog.title}</span>
                <span className="overflow-hidden">{blog.content}</span>
              </div>
            </Link>
          );
        })}
      </div>
      <div className="flex left-0 right-0 bottom-0 fixed items-center justify-center p-2">
        <div className="flex justify-center bg-slate-300 dark:bg-slate-950/50 px-10 py-1 gap-3 rounded">
          <p
            className={`flex p-1 rounded aspect-square h-8 items-center justify-center cursor-pointer`}
            onClick={() => {
              if (page > 1) {
                setPage((prev) => prev - 1);
              } else {
                setPage(1);
              }
            }}
          >
            Prev
          </p>
          {pages > 1 &&
            Array.from({ length: pages }).map((_, index) => {
              return (
                <p
                  className={`flex ${index === page - 1 ? "bg-slate-950 dark:bg-slate-400 text-white dark:text-black" : ""} p-1 rounded aspect-square h-8 items-center justify-center cursor-pointer`}
                  onClick={() => {
                    setPage(index + 1);
                  }}
                >
                  {index + 1}
                </p>
              );
            })}
          <p
            className={`flex p-1 rounded aspect-square h-8 items-center justify-center cursor-pointer`}
            onClick={() => {
              if (page < pages) {
                setPage((prev) => prev + 1);
              } else {
                setPage(pages);
              }
            }}
          >
            Next
          </p>
        </div>
      </div>
      <ToastContainer />
    </div>
  );
}

// src/routes/user/blogs.svelte
<script lang="ts">
	import Card from "@/components/card.svelte";
	import HomeButton from "@/components/home-button.svelte";
	import { get } from "@/lib/fetch.ts";
	import { onMount } from "svelte";
	import { push } from "svelte-spa-router";

	let blogs: Record<string, any>[] = [];
	let pages: number = 1;
	let page: number = 1;

	onMount(async () => {
		const data = await get("blog", {
			page: page,
			limit: 9,
		});
		pages = data.pages;
		blogs = data.data;
	});

	async function changepage(p: number) {
		page = p;
		const data = await get("blog", {
			page: page,
			limit: 9,
		});
		pages = data.pages;
		blogs = data.data;
	}
</script>

<div
	id="blogs"
	class="flex flex-col w-full h-full gap-2 overflow-hidden overflow-y-auto snap-start"
>
	<HomeButton title="Blogs Lists" />
	<div class="flex flex-wrap p-5 gap-5 py-[5%] w-full h-full">
		{#each blogs as blog}
			<Card
				class_="aspect-video w-full md:w-[calc(33.333%-1rem)] justify-between cursor-pointer"
				onclick={() => {
					push(`/blog/${blog.id}`);
				}}
			>
				<span class="font-bold text-[1.25rem]">{blog.title}</span>
				<span class="italic text-[0.75rem]"
					>{blog.content.substring(0, 250)} ...</span
				>
			</Card>
		{/each}
	</div>
	<div class="flex fixed z-10 bottom-0 left-0 right-0 justify-center p-4">
		<div
			class="flex gap-2 bg-[#f0f8ff]/75 dark:bg-[#121212]/75 shadow shadow-[#252525] backdrop-blur-xs rounded-full p-2 px-5"
		>
			<span
				class="cursor-pointer select-none flex items-center justify-center"
				onclick={() => {
					changepage(page > 1 ? page - 1 : 1);
				}}>Prev</span
			>
			{#each Array(pages) as _, p}
				<span
					onclick={() => {
						changepage(p + 1);
					}}
					class={`${p + 1 === page ? "dark:bg-[#555555]" : ""} flex items-center justify-center text-center rounded-full aspect-square w-7 h-7 cursor-pointer select-none`}
				>
					{p + 1}
				</span>
			{/each}
			<span
				class="cursor-pointer select-none flex items-center justify-center"
				onclick={() => {
					changepage(page < pages ? page + 1 : pages);
				}}>Next</span
			>
		</div>
	</div>
</div>
