// src/routes/user/certificates.svelte
<script lang="ts">
  import Card from "@/components/card.svelte";
  import HomeButton from "@/components/home-button.svelte";
  import Loader from "@/components/loader.svelte";
  import { get, retrieval } from "@/lib/fetch.ts";
  import { onMount } from "svelte";
  import { Toaster, toast } from "svelte-french-toast";

  let certs = $state<any[]>([]);
  let pages = $state<number>(1);
  let page = $state<number>(1);

  let loading = $state(true);
  const limit = 8;

  onMount(async () => {
    const api = await get("certs", {
      limit: limit,
      page: page,
    });
    if (api.error) {
      toast.error(api.error, {
        position: "bottom-right",
      });
    } else {
      certs = api.data;
      pages = api.pages;
      loading = false;
    }
  });

  async function changepage(p: number) {
    loading = true;
    page = p;
    const data = await get("certs", {
      page: page,
      limit: limit,
    });
    pages = data.pages;
    certs = data.data;
    loading = false;
  }
</script>

<div
  class="flex flex-wrap p-2 w-full h-full gap-2 overflow-hidden overflow-y-auto pt-[5%]"
>
  <HomeButton
    title="Certificates"
    description="Lists of Ryann Kim's certifications"
    past="/"
  />
  <div class="flex flex-wrap gap-5 py-[2%] p-5 items-start">
    {#if loading}
      {#each Array(limit) as _, i (i)}
        <Loader
          class="aspect-video w-full md:w-[calc(25%-1rem)] items-center justify-center"
        ></Loader>
      {/each}
    {:else}
      {#each certs as cert}
        <Card
          onclick={() => {
            cert.link ? window.open(cert.link, "_blank") : null;
          }}
          class="flex flex-wrap w-full md:w-[calc(25%-1rem)] h-fit rounded !p-0 overflow-none"
        >
          <img
            class="h-full w-full"
            src={cert.url.startsWith("http")
              ? cert.url
              : retrieval("retrieve", { file: cert.url ?? "" })}
            alt={cert.source}
          />
        </Card>
      {/each}
    {/if}
  </div>
  <div class="flex fixed z-10 bottom-0 left-0 right-0 justify-center p-4">
    <div
      class="flex gap-2 bg-[#f0f8ff]/75 dark:bg-[#121212]/75 shadow shadow-[#252525] backdrop-blur-xs rounded-full p-2 px-5"
    >
      <span
        class="cursor-pointer select-none flex items-center justify-center"
        onclick={() => {
          changepage(page > 1 ? page - 1 : 1);
        }}
        onkeydown={(e) => {
          if (e.key === "Enter" || e.key === " ")
            changepage(page > 1 ? page - 1 : 1);
        }}>Prev</span
      >
      {#each Array(pages) as _, p}
        <!-- svelte-ignore a11y_no_static_element_interactions -->
        <span
          onclick={() => {
            changepage(p + 1);
          }}
          onkeydown={(e) => {
            if (e.key === "Enter" || e.key === " ") changepage(p + 1);
          }}
          class={`${p + 1 === page ? "bg-[#cacdcc] dark:bg-[#555555]" : ""} flex items-center justify-center text-center rounded-full aspect-square w-7 h-7 cursor-pointer select-none`}
        >
          {p + 1}
        </span>
      {/each}
      <span
        class="cursor-pointer select-none flex items-center justify-center"
        onclick={() => {
          changepage(page < pages ? page + 1 : pages);
        }}
        onkeydown={(e) => {
          if (e.key === "Enter" || e.key === " ")
            changepage(page < pages ? page + 1 : pages);
        }}>Next</span
      >
    </div>
  </div>
  <Toaster />
</div>

// src/components/index/certificates.tsx
import Title from "@/components/widgets/title";
import type { certsInterface } from "@/interface";
import { retrieval } from "@/lib/api";
import { useState } from "react";
import Modal from "@/components/widgets/modal";
import { Link } from "react-router";

export default function Certificates({ data }: { data: certsInterface[] }) {
  const [visible, setVisible] = useState(false)
  const [certificate, setCertificate] = useState<certsInterface | null>(null)

  return (
    <div className="bg-bg flex flex-col items-center w-full min-h-full">
      <Title id="certificates">Some Certificates</Title>
      <div className="flex flex-wrap justify-center w-full gap-2 p-3 py-5">
        {
          data.map((c: certsInterface, i: number) => {
            return (
              <div
                onClick={() => {
                  setVisible(true)
                  setCertificate(c)
                }}
                className="relative w-[calc(90%-0.5rem)] lg:w-[calc(33.333%-0.5rem)] aspect-video group"
                key={`${i + 1}. ${c.source}`}>
                <img
                  className="absolute object-cover inset-0 h-full w-full"
                  src={c.url.startsWith("http")
                    ? c.url
                    : retrieval("retrieve", { file: c.url ?? "" })} />
                <span
                  onClick={() => {
                    const target = c.link || (c.url.startsWith("http") ? c.url : retrieval("retrieve", { file: c.url }));
                    if (target) window.open(target, "_blank");
                  }}
                  className="absolute select-none cursor-pointer opacity-0 group-hover:opacity-100 bottom-0 p-3 z-10 w-full bg-bg/75 transition-all delay-75">
                  {c.source} [{c.category}]
                </span>
              </div>
            )
          })
        }
        <Link
          to="/certificates"
          className="text-center w-full p-3 silk card">See more</Link>
      </div>

      <Modal
        visible={visible}
        className="flex flex-col relative rounded-md w-2/3 aspect-video overflow-hidden"
        setVisible={setVisible}>
        {certificate ?
          <>
            <img
              className="inset-0 w-full h-full object-fill"
              src={certificate.url.startsWith("http") ? certificate.url : retrieval("/retrieve", { file: certificate.url })}
              alt={certificate.source} />

            <div
              onClick={() => {
                {
                  certificate.link ?
                    window.open(certificate.link, "_blank")
                    : null
                }
              }}
              className="flex flex-col absolute bottom-0 right-0 left-0 z-1 bg-input/75 backdrop-blur-md p-2 cursor-pointer">
              <span>{certificate.source}</span>
              <span>{certificate.category}</span>
            </div>
          </>
          : null
        }
      </Modal>
    </div >
  )
}
