// src/routes/home/hero.svelte
<script lang="ts">
	import Dark from "@/assets/dark.png"
</script>

<div id="hero" class="flex items-center h-full w-full">
	<div class="flex flex-col justify-center items-center md:items-end w-full h-full gap-2 md:gap-5 p-2">
		<h1 class="text-[2em] w-5/6 md:text-[3em] md:w-5/6 text-center md:text-end md:mt-[calc(25%-1rem)]">
      Ryann Kim M. Sesgundo
    </h1>
    <h3 class="text-[0.75em] md:text-[1.75em] text-center md:text-end">
      A Full-Stack Software Developer
    </h3>
  </div>
  <div class="md:flex-col hidden md:flex w-full h-full items-start justify-start p-2">
		<img class={`rounded-md hidden dark:inline h-[calc(75%-0.5rem)] mt-[calc(20%-1rem)]`} src={Dark} alt="">
	</div>
</div>

// src/components/index/hero.tsx
import Img from "@/assets/hero.png";

export default function Hero() {
  return (
    <div className="flex flex-col items-center justify-end w-full h-full">
      <div className="flex flex-col scroll items-center justify-center w-full h-[25%] bg-bg">
        <div className="flex h-1/2 justify-center w-full scrollbox">
          <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path
              d="M0 0h24v24H0z"
              fill="none">
            </path>
            <path
              className="path"
              d="M11.9997 13.1716L7.04996 8.22186L5.63574 9.63607L11.9997 16L18.3637 9.63607L16.9495 8.22186L11.9997 13.1716Z">
            </path>
          </svg>
        </div>
        <span className="text-lg">Scroll down to explore</span>
      </div>
    </div>
  )
}
