// src/routes/admin/contact.svelte
<script lang="ts">
  import { adminGet } from "@/lib/fetch.ts";
  import { session } from "@/lib/storage";

  let data = $state([]);
  let code = $state(session("admin")?.toString() ?? "");

  $effect(async () => {
    const req = await adminGet("/contact", code);
    data = req.data;
  });
</script>

<div class="h-full w-full flex items-center justify-center p-6 pt-20">
  <div
    class="w-full max-w-4xl rounded-2xl border border-zinc-800 bg-zinc-50 dark:bg-zinc-900/70 backdrop-blur-xl shadow-2xl p-8 flex flex-col h-[80vh] overflow-hidden"
  >
    <div class="mb-8 flex items-center justify-between">
      <div>
        <h1 class="text-3xl font-bold dark:text-zinc-200">User Messages</h1>
        <p class="text-zinc-500 mt-2">
          View and manage inquiries from your portfolio
        </p>
      </div>
      <div
        class="bg-zinc-200 dark:bg-zinc-800 px-4 py-2 rounded-xl border border-zinc-300 dark:border-zinc-700"
      >
        <span
          class="text-sm font-bold dark:text-zinc-400 uppercase tracking-widest"
          >Total: {data.length}</span
        >
      </div>
    </div>

    <div class="flex-1 overflow-y-auto space-y-4 custom-scrollbar pr-2">
      {#each data as msg}
        <div
          class="rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-white/40 dark:bg-zinc-800/40 p-6 transition hover:border-zinc-400 dark:hover:border-zinc-600 group"
        >
          <div class="flex items-center justify-between mb-4">
            <div class="flex items-center gap-4">
              <div
                class="h-12 w-12 rounded-xl bg-zinc-200 dark:bg-zinc-700 flex items-center justify-center text-xl text-zinc-500 group-hover:text-zinc-700 dark:group-hover:text-zinc-200 transition-colors"
              >
                <i class="fa-solid fa-user"></i>
              </div>
              <div>
                <h3 class="font-bold text-lg dark:text-zinc-100">{msg.name}</h3>
                <p class="text-sm text-zinc-500 font-medium">{msg.email}</p>
              </div>
            </div>
            <button
              class="text-xs font-bold uppercase tracking-widest text-zinc-400 hover:text-red-500 transition-colors"
            >
              Delete
            </button>
          </div>
          <div
            class="bg-zinc-100/50 dark:bg-zinc-900/50 rounded-xl p-4 border border-zinc-200/50 dark:border-zinc-700/50"
          >
            <p class="text-zinc-700 dark:text-zinc-300 leading-relaxed italic">
              "{msg.content}"
            </p>
          </div>
        </div>
      {/each}
    </div>
  </div>
</div>

// src/pages/admin/contact.tsx
import { useState } from "react";
import { contact } from "../../utils/interfaces";
import { adminGet } from "../../utils/api";
import Input from "../../widgets/input";
import { toast } from "react-toastify";

export default function Contact() {
  const [list, setList] = useState<contact[]>([]);
  const [code, setCode] = useState({ code: "" });
  const [feed, setFeed] = useState(false);

  const fetchContact = async () => {
    setFeed(true);
    const data = await adminGet("contact", code.code);
    if (data.error) {
      toast(data.error);
    } else {
      setList(data.data);
    }
  };

  return (
    <div className="flex flex-col gap-2 w-full items-start h-full">
      <h1 className="text-center text-xl">People who contacted you</h1>
      {!feed ? (
        <div className="flex flex-col items-center w-full h-full gap-2">
          <Input value={code} onChange={setCode} name="code">
            Code
          </Input>
          <button onClick={fetchContact}>Submit</button>
        </div>
      ) : (
        <div className="flex flex-col items-center w-full h-full gap-2">
          {list.map((c) => {
            return (
              <div className="flex flex-col aspect-video bg-zinc-200 w-1/3 shadow-sm shadow-black text-black dark:bg-slate-900 dark:border dark:border-slate-500 dark:border-solid dark:text-white p-4 rounded-lg overflow-hidden gap-1">
                <span className="text-sm">
                  {c.name} - {c.email}
                </span>
                <span className="border-l borderl-l-3 border-l-black dark:border-l-white h-full w-full pl-2">
                  {c.content}
                </span>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
