// src/routes/admin/upload.svelte
<script lang="ts">
	import Input from "@/components/input.svelte";
	import { adminPostMultipart } from "@/lib/fetch";
	import toast from "svelte-french-toast";
	let file_code = $state("");
	let code = $state("");
	let file = $state<FileList | null>(null);
	let sending = $state(false);

	$effect(() => {
		if (file && file.length > 0) {
			console.log(file[0]);
		}
	});

	async function uploadFile() {
		if (!file) {
			toast("No file selected");
			return;
		}

		const formData = new FormData();
		formData.append("file", file[0] as Blob);

		sending = true;
		const res = await adminPostMultipart("upload/submit", code, formData);
		console.error(res);
		sending = false;

		if (res?.error) {
			toast(res.error);
		}

		if (res?.from.description) {
			toast(res.from.description);
			sending = false;
			return;
		}

		const file_ = res?.from.result;
		if (file_.video) {
			file_code = file_.video.file_id;
		} else if (file_.document) {
			file_code = file_.document.file_id;
		} else {
			const f = file_.photo;
			file_code = f[f.length - 1].file_id;
		}
	}
</script>

<div class="min-h-screen w-full flex items-center justify-center p-6">
	<div
		class="w-full max-w-2xl rounded border border-zinc-800 backdrop-blur-xl shadow-2xl p-8"
	>
		<div class="mb-8 text-center">
			<h1 class="text-3xl font-bold text-white">Upload File</h1>
			<p class="text-zinc-400 mt-2">Securely upload and manage your files</p>
		</div>

		<div class="flex flex-col gap-6">
			<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
				<div class="flex flex-col gap-2">
					<label class="text-sm font-medium text-zinc-300"> File Code </label>
					<Input
						class="w-full rounded-xl border border-zinc-700 bg-zinc-800 text-white placeholder:text-zinc-500 focus:ring-2 focus:ring-blue-500"
						name="file_code"
						placeholder=""
						bind:value={file_code}
					/>
				</div>

				<div class="flex flex-col gap-2">
					<label class="text-sm font-medium text-zinc-300"> Admin Code </label>
					<Input
						class="w-full rounded-xl border border-zinc-700 bg-zinc-800 text-white placeholder:text-zinc-500 focus:ring-2 focus:ring-blue-500"
						name="code"
						type="password"
						placeholder=""
						bind:value={code}
					/>
				</div>
			</div>

			<div
				class="flex flex-col items-center justify-center gap-4 rounded-2xl border-2 border-dashed border-zinc-700 bg-zinc-800/50 p-8 transition hover:border-white hover:bg-zinc-800"
			>
				<div class="text-center">
					<h2 class="text-lg font-semibold text-white">Choose a file</h2>
					<p class="text-sm text-zinc-400">
						Drag and drop or browse from your device
					</p>
				</div>

				<Input
					class="w-full cursor-pointer rounded-xl border border-zinc-700 bg-zinc-900 text-zinc-300 file:mr-4 file:rounded-lg file:border-0 file:bg-blue-600 file:px-4 file:py-2 file:text-white hover:file:bg-blue-500"
					name="file"
					placeholder=""
					type="file"
					bind:file
				/>

				{#if file && file.length > 0}
					<div
						class="w-full rounded-xl bg-zinc-900 px-4 py-3 text-sm text-zinc-300 border border-zinc-700"
					>
						Selected File:
						<span class="font-medium text-white">
							{file[0].name}
						</span>
					</div>
				{/if}
			</div>

			<!-- Submit -->
			<button
				onclick={uploadFile}
				class="rounded-2xl bg-white px-6 py-2.5 text-sm font-semibold text-black transition hover:scale-[1.02] hover:bg-white/90 active:scale-[0.98]"
			>
				Upload File
			</button>
		</div>
	</div>
</div>

// src/pages/admin/upload.tsx
import { useState } from "react";
import Input from "../../widgets/input";
import { adminPostMultipart } from "../../utils/api";
import { toast, ToastContainer } from "react-toastify";

export default function UploadImage() {
  const [admin, setAdmin] = useState({
    code: "",
  });
  const [sent, setSent] = useState(false);
  const [sending, setSending] = useState(false);
  const [file, setFile] = useState<File | null>(null);

  const uploadFile = async () => {
    if (!file) {
      toast("No file selected");
      return;
    }
    const formData = new FormData();
    formData.append("file", file);

    setSending(true);
    const res = await adminPostMultipart("upload/submit", admin.code, formData);
    console.error(res);
    setSending(false);
    setSent(true);
    if (res?.error) {
      toast(res.error);
    }

    if (res?.from.description) {
      toast(res.from.description);
      setSending(false);
      return;
    }

    const file_ = res?.from.result;
    if (file_.video) {
      setAdmin({
        code: file_.video.file_id,
      });
    } else if (file_.document) {
      setAdmin({
        code: file_.document.file_id,
      });
    } else {
      const f = file_.photo;
      setAdmin({
        code: f[f.length - 1].file_id,
      });
    }
    toast("File Uploaded Successfully");
  };

  return (
    <div className="flex flex-col items-start justify-center gap-2 rounded min-w-1/3">
      <h1 className="text-xl">Upload Image</h1>
      <div className="flex flex-col items-center h-full w-full gap-2">
        <Input
          type={sent ? "text" : "password"}
          value={admin}
          name="code"
          onChange={setAdmin}
        >
          Code
        </Input>
        <div className="flex flex-col border border-solid border-[#0c0c0c] dark:border-[#f9f9f6] w-full gap-2 rounded-sm">
          <label htmlFor="file" className="text-sm px-4">
            File To Upload
          </label>
          <input
            id="file"
            className="w-full border-none outline-none px-2"
            type="file"
            onChange={async (e: React.ChangeEvent<HTMLInputElement>) => {
              const file = e.target.files?.[0];
              if (file) {
                setFile(file);
              }
            }}
          />
        </div>
        {sending ? (
          <span>Sending</span>
        ) : (
          <button
            onClick={uploadFile}
            type="submit"
            className="p-2 border border-black dark:border-white border-solid w-full rounded-sm"
          >
            Upload image
          </button>
        )}
      </div>
      <ToastContainer />
    </div>
  );
}
