// src/routes/user/blogs.svelte
<script lang="ts">
	import Card from "@/components/card.svelte";
	import HomeButton from "@/components/home-button.svelte";
	import { get } from "@/lib/fetch.ts";
	import { onMount } from "svelte";
	import { push } from "svelte-spa-router";

	let blogs = $state<Record<string, any>[]>([]);
	let pages = $state<number>(1);
	let page = $state<number>(1);

	onMount(async () => {
		const data = await get("blog", {
			page: page,
			limit: 9,
		});
		pages = data.pages;
		blogs = data.data;
	});

	async function changepage(p: number) {
		page = p;
		const data = await get("blog", {
			page: page,
			limit: 9,
		});
		pages = data.pages;
		blogs = data.data;
	}
</script>

<div
	id="blogs"
	class="flex flex-col w-full h-full gap-2 overflow-hidden overflow-y-auto"
>
	<HomeButton title="Blogs Lists" />
	<div class="flex flex-wrap p-5 gap-5 py-[5%] w-full h-full">
		{#each blogs as blog}
			<Card
				class="aspect-video w-full md:w-[calc(33.333%-1rem)] justify-between cursor-pointer"
				onclick={() => {
					push(`/blog/${blog.id}`);
				}}
			>
				<span class="font-bold text-[1.25rem]">{blog.title}</span>
				<span class="italic text-[0.75rem]"
					>{blog.content.substring(0, 250)} ...</span
				>
			</Card>
		{/each}
	</div>
	<div class="flex fixed z-10 bottom-0 left-0 right-0 justify-center p-4">
		<div
			class="flex gap-2 bg-[#f0f8ff]/75 dark:bg-[#121212]/75 shadow shadow-[#252525] backdrop-blur-xs rounded-full p-2 px-5"
		>
			<!-- svelte-ignore a11y_no_static_element_interactions -->
			<span
				class="cursor-pointer select-none flex items-center justify-center"
				onclick={() => {
					changepage(page > 1 ? page - 1 : 1);
				}}
				onkeydown={(e) => {
					if (e.key === "Enter" || e.key === " ")
						changepage(page > 1 ? page - 1 : 1);
				}}>Prev</span
			>
			{#each Array(pages) as _, p}
				<!-- svelte-ignore a11y_no_static_element_interactions -->
				<span
					onclick={() => {
						changepage(p + 1);
					}}
					onkeydown={(e) => {
						if (e.key === "Enter" || e.key === " ") changepage(p + 1);
					}}
					class={`${p + 1 === page ? "bg-[#cacdcc] dark:bg-[#555555]" : ""} flex items-center justify-center text-center rounded-full aspect-square w-7 h-7 cursor-pointer select-none`}
				>
					{p + 1}
				</span>
			{/each}
			<!-- svelte-ignore a11y_no_static_element_interactions -->
			<span
				class="cursor-pointer select-none flex items-center justify-center"
				onclick={() => {
					changepage(page < pages ? page + 1 : pages);
				}}
				onkeydown={(e) => {
					if (e.key === "Enter" || e.key === " ")
						changepage(page < pages ? page + 1 : pages);
				}}>Next</span
			>
		</div>
	</div>
</div>

// src/routes/users/blogs.tsx
import { Markdown, MarkdownExcerpt } from "@/components/widgets/markdown"
import Modal from "@/components/widgets/modal"
import type { blogInterface } from "@/interface"
import { get } from "@/lib/api"
import { House } from "lucide-react"
import { useEffect, useState } from "react"
import { Link, useSearchParams } from "react-router"

export default function Blogs() {
  const [searchParams] = useSearchParams()
  const p = searchParams.get("p") ?? "1"
  const v = searchParams.get("v")

  const [blogs, setBlogs] = useState<blogInterface[]>([])
  const [blog, setBlog] = useState<blogInterface | null>(null)
  const [pages, setPages] = useState(0)

  useEffect(() => {
    (async () => {

      if (v) {
        const { data: b } = await get("blog", {
          id: v
        })
        if (b) {
          setBlog(b as blogInterface)
        }
      }

      let _p = p ?? "1"
      let page = 1
      try {
        page = parseInt(_p)
      } catch (_) { }
      const data = await get("blog", {
        limit: 6,
        page: page
      })
      console.log(data.pages)
      if (data.pages) {
        setPages(data.pages)
      }
      if (data.data) {
        setBlogs(data.data as blogInterface[])
      }
    })()
  }, [])

  useEffect(() => {
    (async () => {

      if (v) {
        const { data: b } = await get("blog", {
          id: v
        })
        if (b) {
          setBlog(b as blogInterface)
        }
      }

      let _p = p ?? "1"
      let page = 1
      try {
        page = parseInt(_p)
      } catch (_) { }
      const data = await get("blog", {
        limit: 6,
        page: page
      })
      console.log(data.pages)
      if (data.pages) {
        setPages(data.pages)
      }
      if (data.data) {
        setBlogs(data.data as blogInterface[])
      }
    })()
  }, [p, v])

  function viewBlog(id: number) {
    const hash = window.location.hash;
    const [path, queryString] = hash.split("?");
    const params = new URLSearchParams(queryString || "");
    if (id < 0) {
      params.delete("v");
      window.location.hash = `${path}?${params.toString()}`;
      window.location.reload()
    } else {
      params.set("v", id.toString());
      window.location.hash = `${path}?${params.toString()}`;
    }
  }

  function setPage(page: number) {
    const hash = window.location.hash; // #/blogs?p=2
    const [path, queryString] = hash.split("?");
    const params = new URLSearchParams(queryString || "");
    params.set("p", page.toString())
    window.location.hash = `${path}?${params.toString()}`
    // window.location.reload()
  }

  return (
    <div className="flex flex-wrap items-center justify-center w-full h-full gap-5 p-5 overflow-y-auto overflow-x-hidden">
      {blogs.length > 0 ?
        blogs.map((b: blogInterface, i: number) => {
          return (
            <div
              className="flex flex-col relative group w-[calc(90%-0.5rem)] lg:w-[calc(33.333%-1rem)] card p-3 aspect-video gap-3 overflow-hidden"
              key={`${i + 1}. ${b.title}`}>
              <span className="text-[1.25rem]">{b.title.substring(0, 70)} {b.title.length > 70 ? "..." : ""}</span>
              <MarkdownExcerpt
                // onClick={() => {
                //   c.link ? window.open(c.link, "_blank") : c.url
                // }}
                content={`${b.content}`} />
              <button
                onClick={() => {
                  viewBlog(b.id)
                }}
                className="absolute silk cursor-pointer bg-linear-to-b from-bg-75 to-bg p-2 opacity-100 md:opacity-0 md:group-hover:opacity-100 bottom-0 right-0 left-0 z-10 transition-all delay-75">View</button>
            </div>
          )
        })
        : null
      }
      {
        pages > 0 ?
          <div className="flex justify-center fixed z-10 bottom-0 right-0 left-0 p-2">
            <div className="flex items-center justify-center bg-card/80 p-2 rounded px-2 gap-3">
              <Link to="/"
                className={` rounded px-2 cursor-pointer`}
              >
                <House />
              </Link>
              {
                Array.from({ length: pages }).map((_, i: number) => {
                  return (
                    <span
                      className={`${p == (i + 1).toString() ? "bg-fg text-bg" : ""} rounded px-2 cursor-pointer`}
                      onClick={() => {
                        setPage(i + 1)
                      }}
                    >{i + 1}</span>
                  )
                })
              }
            </div>
          </div>
          : null
      }
      {
        blog ?
          <Modal visible={blog !== null} setVisible={() => { viewBlog(-1) }}>
            <div className="flex flex-col p-3 flex-1 overflow-hidden">
              <span className="silk pb-2 text-center text-lg w-full border-b border-b-fg border-b-solid">{blog.title}</span>
              <Markdown
                className="flex-1 overflow-y-auto p-5"
                content={blog.content} />
            </div>
          </Modal>
          : null
      }
    </div >
  )
}
