// src/routes/user/certificates.svelte
<script lang="ts">
  import Card from "@/components/card.svelte";
  import HomeButton from "@/components/home-button.svelte";
  import Loader from "@/components/loader.svelte";
  import { get, retrieval } from "@/lib/fetch.ts";
  import { onMount } from "svelte";
  import { Toaster, toast } from "svelte-french-toast";

  let certs = $state<any[]>([]);
  let pages = $state<number>(1);
  let page = $state<number>(1);

  let loading = $state(true);
  const limit = 8;

  onMount(async () => {
    const api = await get("certs", {
      limit: limit,
      page: page,
    });
    if (api.error) {
      toast.error(api.error, {
        position: "bottom-right",
      });
    } else {
      certs = api.data;
      pages = api.pages;
      loading = false;
    }
  });

  async function changepage(p: number) {
    loading = true;
    page = p;
    const data = await get("certs", {
      page: page,
      limit: limit,
    });
    pages = data.pages;
    certs = data.data;
    loading = false;
  }
</script>

<div
  class="flex flex-wrap p-2 w-full h-full gap-2 overflow-hidden overflow-y-auto pt-[5%]"
>
  <HomeButton
    title="Certificates"
    description="Lists of Ryann Kim's certifications"
    past="/"
  />
  <div class="flex flex-wrap gap-5 py-[2%] p-5 items-start">
    {#if loading}
      {#each Array(limit) as _, i (i)}
        <Loader
          class="aspect-video w-full md:w-[calc(25%-1rem)] items-center justify-center"
        ></Loader>
      {/each}
    {:else}
      {#each certs as cert}
        <Card
          onclick={() => {
            cert.link ? window.open(cert.link, "_blank") : null;
          }}
          class="flex flex-wrap w-full md:w-[calc(25%-1rem)] h-fit rounded !p-0 overflow-none"
        >
          <img
            class="h-full w-full"
            src={cert.url.startsWith("http")
              ? cert.url
              : retrieval("retrieve", { file: cert.url ?? "" })}
            alt={cert.source}
          />
        </Card>
      {/each}
    {/if}
  </div>
  <div class="flex fixed z-10 bottom-0 left-0 right-0 justify-center p-4">
    <div
      class="flex gap-2 bg-[#f0f8ff]/75 dark:bg-[#121212]/75 shadow shadow-[#252525] backdrop-blur-xs rounded-full p-2 px-5"
    >
      <span
        class="cursor-pointer select-none flex items-center justify-center"
        onclick={() => {
          changepage(page > 1 ? page - 1 : 1);
        }}
        onkeydown={(e) => {
          if (e.key === "Enter" || e.key === " ")
            changepage(page > 1 ? page - 1 : 1);
        }}>Prev</span
      >
      {#each Array(pages) as _, p}
        <!-- svelte-ignore a11y_no_static_element_interactions -->
        <span
          onclick={() => {
            changepage(p + 1);
          }}
          onkeydown={(e) => {
            if (e.key === "Enter" || e.key === " ") changepage(p + 1);
          }}
          class={`${p + 1 === page ? "bg-[#cacdcc] dark:bg-[#555555]" : ""} flex items-center justify-center text-center rounded-full aspect-square w-7 h-7 cursor-pointer select-none`}
        >
          {p + 1}
        </span>
      {/each}
      <span
        class="cursor-pointer select-none flex items-center justify-center"
        onclick={() => {
          changepage(page < pages ? page + 1 : pages);
        }}
        onkeydown={(e) => {
          if (e.key === "Enter" || e.key === " ")
            changepage(page < pages ? page + 1 : pages);
        }}>Next</span
      >
    </div>
  </div>
  <Toaster />
</div>

// src/routes/users/certificates.tsx
import Modal from "@/components/widgets/modal"
import type { certsInterface } from "@/interface"
import { get, retrieval } from "@/lib/api"
import { ArrowLeft } from "lucide-react"
import { useEffect, useState } from "react"
import { useNavigate } from "react-router"

export default function UserCertifications() {
  const [visible, setVisible] = useState(false)
  const navigation = useNavigate()
  const [selectedCert, setSelectedCert] = useState<certsInterface | null>(null)
  const [currentPage] = useState(1)
  const [certis, setCertis] = useState<certsInterface[]>([])

  useEffect(() => {
    (async () => {
      const data = await get("certs", {
        page: currentPage,
        limit: 6
      })
      console.log(data)
      if (data.data) {
        setCertis(data.data as certsInterface[])
      }
    })()
  }, [currentPage])

  return (
    <div className="flex md:flex-col w-full h-full overflow-y-auto gap-3 md:gap-0">
      <div
        className={`flex flex-col md:flex-row w-[calc(20%-0.5rem)] md:w-full gap-2 p-3 sticky md:z-20 bg-bg top-0 md:left-0 md:right-0`}>
        <span
          onClick={() => {
            navigation("/")
          }}
          className="text-xs">
          <ArrowLeft />
        </span>
      </div>
      <div className="flex flex-wrap w-full gap-2 p-3 py-[2rem]">
        {
          certis.map((c: certsInterface, i: number) => {
            return (
              <span
                onClick={() => {
                  setVisible(true)
                  setSelectedCert(c)
                }}
                className="relative w-[calc(90%-0.5rem)] md:w-[calc(33.333%-0.5rem)] aspect-video group overflow-hidden"
                key={`${i + 1}.${c.source}`}>
                <img
                  className="absolute object-cover inset-0 h-full w-full"
                  src={c.url.startsWith("http")
                    ? c.url
                    : retrieval("retrieve", { file: c.url ?? "" })} />
                <span
                  className="absolute select-none cursor-pointer opacity-0 group-hover:opacity-100 bottom-0 p-3 z-10 w-full bg-bg/75 transition-all delay-75">
                  {c.source}
                </span>
              </span>
            )
          })
        }
      </div>
      <Modal
        visible={visible}
        className="flex flex-col relative rounded-md w-2/3 aspect-video overflow-hidden"
        setVisible={setVisible}>

        {selectedCert ?
          <>
            <img
              className="absolute object-fill inset-0 h-full w-full"
              src={selectedCert.url.startsWith("http")
                ? selectedCert.url
                : retrieval("retrieve", { file: selectedCert.url ?? "" })} />
            <div
              onClick={() => {
                selectedCert.url ? window.open(selectedCert.url, "_blank") : null
              }}
              className="flex flex-col absolute bottom-0 right-0 left-0 z-1 bg-input/50 backdrop-blur-md p-2 cursor-pointer">
              <span>{selectedCert.source}</span>
              <span>{selectedCert.category}</span>
            </div>
          </>
          : null
        }
      </Modal>
    </div>
  )
}
