// src/routes/home/projects.svelte
<script lang="ts">
	import { retrieval } from "@/lib/fetch.ts";
	import Loader from "@/components/loader.svelte";
	import Card from "@/components/card.svelte";

	let {
		categories = ["all"],
		totalProjects = [],
		projects = $bindable([]),
		parseData = false,
	}: {
		categories?: string[];
		totalProjects?: Record<string, any>[];
		projects?: Record<string, any>[];
		parseData?: boolean;
	} = $props();

	let active = $state("all");

	function filter(category: string) {
		active = category.toLowerCase();
		projects = totalProjects.filter((proj: Record<string, any>) =>
			active === "all" ? true : proj.category.includes(active.toLowerCase()),
		);
	}
</script>

<div
	id="projects"
	class="flex flex-col p-2 pt-[25%] md:pt-[10%] h-full w-full overflow-y-auto snap-start select-none"
>
	<div
		class="flex gap-2 items-center md:justify-center py-10 md:p-3 overflow-hidden overflow-x-auto scrollbar-none"
	>
		{#each categories as category}
			<!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
			<li
				onclick={() => {
					filter(category);
				}}
				onkeydown={(e) => {
					if (e.key === "Enter" || e.key === " ") filter(category);
				}}
				class={`select-none cursor-pointer ${active === category.toLowerCase() ? "border border-black dark:border-white border-solid" : "bg-zinc-300 dark:bg-[#313131]"} px-2 rounded list-none text-[0.80em]`}
			>
				{#if category.length <= 3 && category !== "all"}
					{category.toUpperCase()}
				{:else}
					{category[0].toUpperCase()}{category.substring(1)}
				{/if}
			</li>
		{/each}
	</div>
	<div class="flex flex-wrap w-full gap-5 p-5">
		{#if projects.length > 0}
			{#each projects as project}
				{#if active.toLowerCase() === "all" && project.img}
					<Card
						onclick={() => {
							window.open(project.link, "_blank");
						}}
						class="relative aspect-video w-full md:w-[calc(33.333%-1rem)] rounded overflow-hidden !p-0 group"
					>
						<img
							class="absolute w-full h-full md:grayscale group-hover:grayscale-0"
							src={retrieval("retrieve", { file: project.img ?? "" })}
							alt=""
						/>
						<span
							class="absolute z-1 bottom-0 left-0 right-0 bg-[#212121]/50 text-white p-2 md:opacity-0 group-hover:opacity-100 transition-opacity delay-75"
						>
							{project.name}
						</span>
					</Card>
				{:else if active.toLowerCase() !== "all"}
					<Card
						onclick={() => {
							window.open(project.link, "_blank");
						}}
						class="relative aspect-video w-full md:w-[calc(33.333%-1rem)] rounded overflow-hidden !p-0 group"
					>
						<img
							class="absolute w-full h-full md:grayscale group-hover:grayscale-0"
							src={retrieval("retrieve", { file: project.img ?? "" })}
							alt=""
						/>
						<span
							class="absolute z-1 bottom-0 left-0 right-0 bg-[#212121]/50 text-white p-2 md:opacity-0 dark:group-hover:opacity-100 group-hover:opacity-100 transition-opacity delay-75"
						>
							{project.name}
						</span>
					</Card>
				{/if}
			{/each}
		{:else}
			{#each Array(6) as _, i (i)}
				<Loader class="aspect-video w-full md:w-[calc(33.333%-1rem)]"></Loader>
			{/each}
		{/if}
	</div>
</div>

// src/routes/users/projects.tsx
import type { projectInterface, projectsInterface } from "@/interface"
import { get, retrieval } from "@/utils/api"
import { use, useState } from "react"

const getProject = get("projects")

export default function UserProject() {
  const project = use(getProject).data as projectInterface
  const projects = project.projects.sort((a: projectsInterface, b: projectsInterface) => a.name.localeCompare(b.name)) as projectsInterface[]
  const categories = ["all", ...project.categories] as string[]
  const [search, setSearch] = useState("all")
  const [filtered, setFiltered] = useState(projects)

  function filterProjects(category: string) {
    setSearch(category)
    if (category === "all") {
      setFiltered(projects)
      return
    }
    setFiltered(projects.filter(p => p.category.includes(category)))
  }

  return (
    <div className="flex flex-col w-full h-full overflow-y-auto">
      <div
        className={`flex gap-2 justify-center p-3 sticky z-20 bg-bg top-0 left-0 right-0`}>
        {
          categories.map((c: string, i: number) => {
            return (
              <span
                className={`cursor-pointer ${c === search ? "underline" : ""}`}
                onClick={() => {
                  filterProjects(c.toLowerCase())
                }}
                key={`${i}. ${c}`}
              >{c.toUpperCase()}</span>
            )
          })
        }
      </div>
      <div className="flex flex-wrap w-full gap-2 p-3 py-[2rem]">
        {
          filtered.map((p: projectsInterface, i: number) => {
            return (
              <span
                className="relative w-[calc(90%-0.5rem)] lg:w-[calc(33.333%-0.5rem)] aspect-video group overflow-hidden"
                key={`${i + 1}. ${p.name}`}>
                {p.img ?
                  <img
                    className="absolute object-cover inset-0 h-full w-full lg:dark:grayscale-100 group-hover:grayscale-0 transition delay-75"
                    src={p.img ?
                      retrieval("retrieve", { file: p.img ?? "" }) : ""} />
                  :
                  <span
                    className="absolute flex items-center justify-center border border-solid border-fg object-cover inset-0 h-full w-full lg:dark:grayscale-100 group-hover:grayscale-0 transition delay-75"
                  >
                    No Image Attached
                  </span>
                }
                <span
                  // onClick={() => {
                  //   p.link ? window.open(c.link, "_blank") : c.url
                  // }}
                  className="absolute select-none cursor-pointer opacity-0 group-hover:opacity-100 bottom-0 p-3 z-10 w-full bg-bg/75 transition-all delay-75">
                  {p.name}
                </span>
              </span>
            )
          })
        }
      </div>
    </div>
  )
}
